### ISSUE TITLE
Extract additional tender information

### ISSUE THREAD

**Issue by jomerkel** [jomerkel/eu_tender#13]
Extrect information about the tender process from the detail page in Section V.2.2) Information about tenders.

Example https://ted.europa.eu/udl?uri=TED:NOTICE:125901-2020:TEXT:EN:HTML&tabId=0

<img width="876" alt="Screenshot 2020-03-16 at 17 20 05" src="https://user-images.githubusercontent.com/756627/76778644-77c93e00-67aa-11ea-919e-87a7a126a500.png">

Expected results and new columns:

NrTendersRecieved: 2
NrTendersRecievedSME: 0
NrTendersRecievedoEU: 1
NrTendersRecievednonEU: 0
NrTendersRecievedelectronic: 1
Consortium: No

**Comment by Roman-Kasianenko** [comment]
@jomerkel almost done, need to know in which file those filed should be saved
