### ISSUE TITLE
Change input from advanced search to expert search

### ISSUE THREAD

**Issue by jomerkel** [jomerkel/eu_tender#6]
<img width="337" alt="Screenshot 2020-03-13 at 11 09 22" src="https://user-images.githubusercontent.com/756627/76612429-9ca88180-651c-11ea-83c6-dadb81678d7e.png">

Current search input is based on the advanced search form which is not allowing multiple full text search queries with an OR connection. Therefore the expert search with a dedicated search string needs to be used.

<img width="569" alt="Screenshot 2020-03-13 at 11 19 38" src="https://user-images.githubusercontent.com/756627/76612524-c792d580-651c-11ea-969a-d7e9297ac0bc.png">

At the moment only two parameters are interesting for the ARCHIVE selection:
FT (Fulltext): Multiple search terms which are connected by an OR
PC (CPV Codes): Multiple CPV codes. CPV codes can be shortened and generalized with an asterrix *

During manual testing an errror occurred several times in the frontend with the error code ") paranthesis missing in arguments list". The example above is working and should be used for search input testing. 

Expected result list should be as following:

<img width="546" alt="Screenshot 2020-03-13 at 11 19 51" src="https://user-images.githubusercontent.com/756627/76612718-26584f00-651d-11ea-98e6-a4cf449929be.png">

**Comment by Roman-Kasianenko** [comment]
Fixed at https://github.com/jomerkel/eu_tender/pull/9
