### ISSUE TITLE
Crawl all paginated results

### ISSUE THREAD

**Issue by jomerkel** [jomerkel/eu_tender#7]
Ensure crawling of all paginated results with the current methodology and data results:

Example query:
<img width="569" alt="Screenshot 2020-03-13 at 11 19 38" src="https://user-images.githubusercontent.com/756627/76612792-4851d180-651d-11ea-87e2-b799e3dde32a.png">

Example result list should contain of 2343 results
<img width="546" alt="Screenshot 2020-03-13 at 11 19 51" src="https://user-images.githubusercontent.com/756627/76612864-67506380-651d-11ea-9220-462c15009175.png">

**Comment by Roman-Kasianenko** [comment]
Fixed at https://github.com/jomerkel/eu_tender/pull/9
